### ISSUE TITLE
Missing ECMAScript 2020+ features 

### ISSUE THREAD

**Issue by adams85** [sebastienros/esprima-dotnet#330]
Readme/description says that the lib fully supports ECMAScript 2019. However, this statement looks a bit outdated in the light of recent additions: AFAICS, almost everything is covered up to ECMAScript 2022 already (albeit still buggy here and there). According to [this source](https://exploringjs.com/impatient-js/ch_new-javascript-features.html#new-in-es2020), here we are currently:

ECMAScript 2020
* [x] Dynamic imports via `import()`
* [x] Import metadata for the current module (`import.meta`)
* [x] Namespace re-exporting (`export * as ns from 'mod';`)
* [x] Optional chaining for property accesses and method calls (`value?.prop`)
* [x] Nullish coalescing operator (??) (`value ?? defaultValue`)
* [x] Bigints – arbitrary-precision integers
* [x] `globalThis` – access the global object that works both on browsers and server-side platforms (Note: as it seems that other parsers also treat this a simple identifier as opposed to some special syntax element like `ThisExpression`, we can consider this done.)

ECMAScript 2021:
* [x] Logical assignment operators (`a ||= b`, `a &&= b`, `a ??= b`)
* [x] Underscores (_) as separators in numeric and bigint literals (`123_456.789_012`, `6_000_000_000_000_000_000_000_000n`)

ECMAScript 2022:
* [x] Instance and static public fields:
    ```js
    class StaticPublicFieldClass {
      /* static */ identifierFieldKey = 1;
      /* static */ 'quoted field key' = 2;
      /* static */ [computedFieldKey] = 3;
    }
    ```
    Note: this looks implemented but buggy. Quoted and computed fields are parsed with error. @lahma Maybe you have something in the works related to this? (I mean #248)
* [x] Private fields, methods and accessors
    ```js
    class C1 {
      /* static */ #p_field = 0;
      /* static */ get #p_getter() {}
      /* static */ set #p_getter(v) {}
      /* static */ #p_method() {}
    }
    ```
    Note: again, implemented but buggy. The resulting AST contains `Identifier`s instead of `PrivateIdentifier`s. (Compare with AST Explorer output.)
* [x] Static initialization blocks
    ```js
    class C1 {
      static {}
    }
    ```
* [x] Private slot checks (`#privateSlot in obj`) Works but private identifier parsed incorrectly as `Identifier`. (Compare with AST Explorer output.)
* [x] Top-level await in modules
* [x] RegExp match indices (`/(a+)(b+)/d`). Implemented by #343

So the lib is ECMAScript 2021 compliant at worst and it looks like we're just a few bugfixes/minor additions away from 2022. What's your opinion, should we chase this for v3?

**Comment by lahma** [comment]
> Note: this looks implemented but buggy. Quoted and computed fields are parsed with error. @lahma Maybe you have something in the works related to this? (I mean https://github.com/sebastienros/esprima-dotnet/pull/248)

Yes that was the original intention some weeks ago when I was planning to improve class support in Jint. Somehow a lot of time has been used to some other areas... I'm sure that's going to be a fun rebase again.

> So the lib is ECMAScript 2021 compliant at worst and it looks like we're just a few bugfixes/minor additions away from 2022. What's your opinion, should we chase this for v3?

All improvements would be nice. It's basically removing things from allow-list.txt currently and re-generating test cases and seeing what is failing. I don't expect many API breaking changes, probably something like AST having `Identifier` and it should start supporting both `Identifier` and `PrivateIdentifier`

**Comment by jogibear9988** [comment]
The Properties I've fixed in esprima-next like this: https://github.com/node-projects/esprima-next/commit/530bbad1a0c0c945fe66f0500e0f1d598ec3d5b2

**Comment by jogibear9988** [comment]
The computed did work already.

**Comment by jogibear9988** [comment]
Also the Private Identifiers are correctly parsed as PrivateIdentifier in Esprima-next and I copied the implementation over...
https://github.com/sebastienros/esprima-dotnet/pull/205
should I look for it, or does anyone already work on this?

**Comment by jogibear9988** [comment]
What do we need to do for "RegExp match indices (/(a+)(b+)/d)"

**Comment by jogibear9988** [comment]
https://github.com/node-projects/esprima-next/commit/2cd2c5ac71eac124b315102147a41dfda4508e9b

**Comment by adams85** [comment]
@jogibear9988 Thanks for chiming in!

> Also the Private Identifiers are correctly parsed as PrivateIdentifier in Esprima-next and I copied the implementation over...
https://github.com/sebastienros/esprima-dotnet/pull/205
should I look for it, or does anyone already work on this?

So this was implemented once and should work. Maybe something has gone off the rails since then. However, I think #248 touches this area so I think we should return to this issue after that PR has got merged.

> What do we need to do for "RegExp match indices (/(a+)(b+)/d)" ?

At a quick glance I think we just need to allow the regex flag `d`.

> https://github.com/node-projects/esprima-next/commit/2cd2c5ac71eac124b315102147a41dfda4508e9b

Hmm, wouldn't be just simpler to set `_context.IsAsync` to `true` at the beginning of `ParseModule`?

**Comment by adams85** [comment]
> do we check the regexes? in esprima-next I had to do nothing

I tested it again and it turned out that it fails only when `AdaptRegexp` is enabled. Otherwise, it's parsed without error. So I suppose the fix will be pretty straightforward.

**Comment by jogibear9988** [comment]
@adams85 some of the issues should be fixed by my new changes

**Comment by adams85** [comment]
@jogibear9988 As I see, you made some corrections around private identifiers. However, it still doesn't look complete, see my comment in #354. Private slot checks (`#privateSlot in obj`) looks ok though. Is there anything else that you set straight?

**Comment by lahma** [comment]
One note, as hindsight is 20-20, one option for ensuring parsing succeeds (regardless if AST is actually correct) one could try to use test262 config file's ExcludedFeatures configuration.

Regenerate suite and remove things from allow list (delete file and regenerate too) and then enable feature again to see failing tests related to feature.

**Comment by jogibear9988** [comment]
@lahma was this comment for this issue?

**Comment by lahma** [comment]
It was a generic comment about utilizing the test suite (maybe) more efficiently.

**Comment by jogibear9988** [comment]
> @jogibear9988 As I see, you made some corrections around private identifiers. However, it still doesn't look complete, see my comment in #354. Private slot checks (`#privateSlot in obj`) looks ok though. Is there anything else that you set straight?

I think the computed props should also work, not yet tested the quoted. private fields work, private slot checks should.
And the top level await was fixed earlier...

so I think this could be closed

**Comment by adams85** [comment]
Private class members seems complete with your recent commit. 👍 

Computed props work but

```js
class StaticPublicFieldClass {
  /* static */ 'quoted field key' = 2;
}
```

still fails.

Top-level awaits won't work either. (I have something in the works regarding this. I may submit a PR soon.)

**Comment by jogibear9988** [comment]
> [node-projects/esprima-next@2cd2c5a](https://github.com/node-projects/esprima-next/commit/2cd2c5ac71eac124b315102147a41dfda4508e9b)

ah, i only fixed it in esprima next

**Comment by lahma** [comment]
I tagged latest main as `v3.0.0-beta-10` and pushing to Jint for dogfooding. There's only some parsing problems left that are of kind "parse failed", others seem to be mostly about missing validation.

The regex parsing fails for at least one test case now, but there's https://github.com/sebastienros/esprima-dotnet/pull/364 for thinking about that.
